# Tomcat
server.port: 8080

# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN

# Spring settings
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/incar_protocol
        username:root
        password:root
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
